import fs from "fs";
import path from "path";

// Sepolia V3 contract addresses
const SEPOLIA_CONTRACTS = {
  AirdropFundsV3: "0x79bf4e98b25d585238066de2bb6984bf885cd379d8fef18f81af559a264c589",
  PredictionMarketV3: "0x2f7d11253b52f0b7b733b5b904bdc3702c833982e5c6e63d7792e6053c483f0",
  GamePaymentHandler: "0x23de23a7f6271e87df4e82c7cff674d0837b2eee12893e4e2ca3fff105b5e6b",
  ColorMatchGameV3: "0x0ec31b78ba4f4ccb1f66aa2c79e485bdfd33d02b8546824c69c1bf5fd631531",
  SpeedMatchGameV3: "0x003d36988097b2afb178518d9a25c4d1d8af9502b903bff87cb160f607ab9678",
  MemoryBlitzGameV3: "0x01fd2685441d644697e0ef58836276f1e4ae0ef5e671bbf265f0d46eb04f072a",
  LeaderboardManager: "0x0088d4670b7a95fa716ea4147bac5043aca8224e23e791cc49965d0a18db101c", // ColorMatch
};

// Devnet placeholder addresses
const DEVNET_CONTRACTS = {
  AirdropFundsV3: "0x1234567890123456789012345678901234567890123456789012345678901234",
  PredictionMarketV3: "0x1234567890123456789012345678901234567890123456789012345678901235",
  GamePaymentHandler: "0x1234567890123456789012345678901234567890123456789012345678901236",
  ColorMatchGameV3: "0x1234567890123456789012345678901234567890123456789012345678901237",
  SpeedMatchGameV3: "0x1234567890123456789012345678901234567890123456789012345678901238",
  MemoryBlitzGameV3: "0x1234567890123456789012345678901234567890123456789012345678901239",
  LeaderboardManager: "0x123456789012345678901234567890123456789012345678901234567890123a",
};

function loadABI(contractName: string) {
  const abiPath = path.join(
    __dirname,
    "../contracts/target/dev",
    `contracts_${contractName}.contract_class.json`
  );

  if (!fs.existsSync(abiPath)) {
    console.warn(`ABI not found for ${contractName} at ${abiPath}`);
    return [];
  }

  const contractClass = JSON.parse(fs.readFileSync(abiPath, "utf8"));
  return contractClass.abi || [];
}

function generateDeployedContracts() {
  const contracts = [
    "AirdropFundsV3",
    "PredictionMarketV3",
    "GamePaymentHandler",
    "ColorMatchGameV3",
    "SpeedMatchGameV3",
    "MemoryBlitzGameV3",
    "LeaderboardManager",
  ];

  const devnetContracts: any = {};
  const sepoliaContracts: any = {};

  for (const contractName of contracts) {
    const abi = loadABI(contractName);

    devnetContracts[contractName] = {
      address: DEVNET_CONTRACTS[contractName as keyof typeof DEVNET_CONTRACTS],
      abi,
    };

    sepoliaContracts[contractName] = {
      address: SEPOLIA_CONTRACTS[contractName as keyof typeof SEPOLIA_CONTRACTS],
      abi,
    };
  }

  const output = `/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: ${JSON.stringify(devnetContracts, null, 2)},
  sepolia: ${JSON.stringify(sepoliaContracts, null, 2)},
} as const;

export default deployedContracts;
`;

  const outputPath = path.join(
    __dirname,
    "../../nextjs/contracts/deployedContracts.ts"
  );

  fs.writeFileSync(outputPath, output, "utf8");
  console.log(`✅ Generated deployedContracts.ts at ${outputPath}`);
  console.log(`✅ Included ${contracts.length} V3 contracts for devnet and sepolia networks`);
}

generateDeployedContracts();
